# Generated by Django 2.1.8 on 2019-04-18 16:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import review.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('rating', review.custom_fields.IntegerRangeField()),
                ('summary', models.TextField(max_length=10000)),
                ('ip_address', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=255)),
                ('submission_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
